version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rafan
      - MONGO_INITDB_ROOT_PASSWORD=rafan123

volumes:
  mongo_data:
